apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  type: LoadBalancer
  selector:
    app: trivial-go-web-app  
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
